# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for mistral.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

release_group: null

images:
  bootstrap: docker.io/kolla/ubuntu-source-mistral-api:3.0.3
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  db_init: docker.io/kolla/ubuntu-source-mistral-api:3.0.3
  db_sync: docker.io/kolla/ubuntu-source-mistral-api:3.0.3
  ks_user: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_service: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_endpoints: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  api: docker.io/kolla/ubuntu-source-mistral-api:3.0.3
  engine: docker.io/kolla/ubuntu-source-mistral-engine:3.0.3
  event_engine: docker.io/kolla/ubuntu-source-mistral-engine:3.0.3
  executor: docker.io/kolla/ubuntu-source-mistral-executor:3.0.3
  pull_policy: "IfNotPresent"

network:
  api:
    ingress:
      public: true
    node_port:
      enabled: false
      port: 28989

bootstrap:
  enabled: false
  script: |
    openstack token issue

dependencies:
  db_init:
    services:
    - service: oslo_db
      endpoint: internal
  db_sync:
    jobs:
    - mistral-db-init
    services:
    - service: oslo_db
      endpoint: internal
  ks_user:
    services:
    - service: identity
      endpoint: internal
  ks_service:
    services:
    - service: identity
      endpoint: internal
  ks_endpoints:
    jobs:
    - mistral-ks-service
    services:
    - service: identity
      endpoint: internal
  api:
    jobs:
    - mistral-db-sync
    - mistral-ks-user
    - mistral-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
  engine:
    jobs:
    - mistral-db-sync
    - mistral-ks-user
    - mistral-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
  event_engine:
    jobs:
    - mistral-db-sync
    - mistral-ks-user
    - mistral-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
  executor:
    jobs:
    - mistral-db-sync
    - mistral-ks-user
    - mistral-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal

# Names of secrets used by bootstrap and environmental checks
secrets:
  identity:
    admin: mistral-keystone-admin
    user: mistral-keystone-user
  oslo_db:
    admin: mistral-db-admin
    user: mistral-db-user

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      user:
        role: admin
        region_name: RegionOne
        username: mistral
        password: password
        project_name: service
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
  workflow:
    name: mistral
    hosts:
      default: mistral-api
      public: mistral
    path:
      default: /v2
    scheme:
      default: 'http'
    port:
      api:
        default: 8989
        public: 80
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: mistral
        password: password
    hosts:
      default: mariadb
    path: /mistral
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    hosts:
      default: rabbitmq
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672
  oslo_cache:
    hosts:
      default: memcached
    port:
      memcache:
        default: 11211

conf:
  policy:
    override:
    append:
  mistral:
    override:
    append:
    default:
      mistral:
        conf:
    api:
      mistral:
        config:
          port: 8989
          api_workers: 8
    coordination:
      mistral:
        config:
          backend_url:
    database:
      oslo:
        db:
          max_retries: -1
    keystone_authtoken:
      keystonemiddleware:
        auth_token:
          auth_type: password
          auth_version: v3

pod:
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  mounts:
    mistral_api:
      init_container: null
      mistral_api:
    mistral_executor:
      init_container: null
      mistral_executor:
    mistral_engine:
      init_container: null
      mistral_engine:
    mistral_event_engine:
      init_container: null
      mistral_event_engine:
    mistral_bootstrap:
      init_container: null
      mistral_bootstrap:
  replicas:
    api: 1
    engine: 1
    event_engine: 1
    executor: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    disruption_budget:
      api:
        min_available: 0
    termination_grace_period:
      api:
        timeout: 30
  resources:
    enabled: false
    api:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    engine:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    event_engine:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    executor:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      bootstrap:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_init:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_endpoints:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_service:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_user:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      tests:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

manifests:
  configmap_bin: true
  configmap_etc: true
  deployment_api: true
  deployment_executor: true
  ingress_api: true
  job_bootstrap: true
  job_db_init: true
  job_db_sync: true
  job_ks_endpoints: true
  job_ks_service: true
  job_ks_user: true
  pdb_api: true
  secret_db: true
  secret_keystone: true
  service_ingress_api: true
  service_api: true
  statefulset_engine: true
  statefulset_event_engine: true
