{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.statefulset_engine }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.engine }}
{{- $mounts_heat_engine := .Values.pod.mounts.heat_engine.heat_engine }}
{{- $mounts_heat_engine_init := .Values.pod.mounts.heat_engine.init_container }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: heat-engine
spec:
  serviceName: heat-engine
  replicas: {{ .Values.pod.replicas.engine }}
  template:
    metadata:
      labels:
{{ tuple $envAll "heat" "engine" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
{{ tuple $envAll "heat" "engine" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_heat_engine_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: heat-engine
          image: {{ .Values.images.engine }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.engine | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - /tmp/heat-engine.sh
          volumeMounts:
            - name: pod-etc-heat
              mountPath: /etc/heat
            - name: pod-var-cache-heat
              mountPath: /var/cache/heat
            - name: heat-bin
              mountPath: /tmp/heat-engine.sh
              subPath: heat-engine.sh
              readOnly: true
            - name: heat-etc
              mountPath: /etc/heat/heat.conf
              subPath: heat.conf
              readOnly: true
            - name: heat-etc
              mountPath: /etc/heat/policy.json
              subPath: policy.json
              readOnly: true
{{- if $mounts_heat_engine.volumeMounts }}{{ toYaml $mounts_heat_engine.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-etc-heat
          emptyDir: {}
        - name: pod-var-cache-heat
          emptyDir: {}
        - name: heat-bin
          configMap:
            name: heat-bin
            defaultMode: 0555
        - name: heat-etc
          configMap:
            name: heat-etc
            defaultMode: 0444
{{- if $mounts_heat_engine.volumes }}{{ toYaml $mounts_heat_engine.volumes | indent 8 }}{{ end }}
{{- end }}
