# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.init }}
{{- $mounts_keystone_db_init := .Values.mounts.keystone_db_init.keystone_db_init }}
{{- $mounts_keystone_db_init_init := .Values.mounts.keystone_db_init.init_container }}

apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies $mounts_keystone_db_init_init | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: keystone-db-init
          image: {{ .Values.images.db_init }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}  
          resources:
            limits:
              cpu: {{ .Values.resources.jobs.init.limits.cpu | quote }}
              memory: {{ .Values.resources.jobs.init.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.jobs.init.requests.cpu | quote }}
              memory: {{ .Values.resources.jobs.init.requests.memory | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:            
{{ toYaml $mounts_keystone_db_init.volumeMounts | indent 12 }}
      volumes:
{{ toYaml $mounts_keystone_db_init.volumes | indent 8 }}

