# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
kind: Service
apiVersion: v1
metadata:
  name: ceph-mon
  labels:
    app: ceph
    daemon: mon
  annotations:
    # In kubernetes 1.6 and beyond, it seems there was a change in behavior
    # requiring us to tolerate unready endpoints to form a quorum, otherwise
    # the ceph-mon headless service will most likely not return enough
    # endpoints to allow a quorum to be formed and most certainly never
    # return a ceph-mons own address to a newly provisioned ceph-mon
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: {{ .Values.network.port.mon }}
    protocol: TCP
    targetPort: {{ .Values.network.port.mon }}
  selector:
    app: ceph
    daemon: mon
  clusterIP: None

{{- if .Values.rgw.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  labels:
    app: ceph
    daemon: rgw
spec:
  ports:
  - port: {{ .Values.network.port.rgw_ingress }}
    protocol: TCP
    targetPort: {{ .Values.network.port.rgw_target }}
  selector:
    app: ceph
    daemon: rgw
{{- end }}
