# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.libvirt }}
{{- $mounts_nova_libvirt := .Values.mounts.nova_libvirt.nova_libvirt }}
{{- $mounts_nova_libvirt_init := .Values.mounts.nova_libvirt.init_container }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-libvirt
spec:
  template:
    metadata:
      labels:
        app: nova-libvirt
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
    spec:
      nodeSelector:
        {{ .Values.labels.agent.libvirt.node_selector_key }}: {{ .Values.labels.agent.libvirt.node_selector_value }}
      securityContext:
        runAsUser: 0
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirst
      containers:
        - name: nova-libvirt
          image: {{ .Values.images.libvirt }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.nova_libvirt.requests.memory | quote }}
              cpu: {{ .Values.resources.nova_libvirt.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.nova_libvirt.limits.memory | quote }}
              cpu: {{ .Values.resources.nova_libvirt.limits.cpu | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /tmp/libvirt.sh
          volumeMounts:
            - name: nova-bin
              mountPath: /tmp/libvirt.sh
              subPath: libvirt.sh
              readOnly: true
            - name: nova-etc
              mountPath: /etc/libvirt/libvirtd.conf
              subPath: libvirtd.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: nova-etc
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
              readOnly: true
            - mountPath: /lib/modules
              name: libmodules
              readOnly: true
            - name: varlibnova
              mountPath: /var/lib/nova
            - name: varliblibvirt
              mountPath: /var/lib/libvirt
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
            - name: cgroup
              mountPath: /sys/fs/cgroup
            {{- if .Values.sdn.opencontrail.enabled }}
            - name: nova-etc
              mountPath: /etc/libvirt/qemu.conf
              subPath: qemu.conf
              readOnly: true
            {{- end }}
            {{- if .Values.ceph.enabled }}
            - name: nova-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/ceph/ceph.client.keyring
              subPath: ceph.client.keyring
              readOnly: true
            {{- end }}
{{ if $mounts_nova_libvirt.volumeMounts }}{{ toYaml $mounts_nova_libvirt.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: nova-bin
          configMap:
            name: nova-bin
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: varlibnova
          hostPath:
            path: /var/lib/nova
        - name: varliblibvirt
          hostPath:
            path: /var/lib/libvirt
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
{{ if $mounts_nova_libvirt.volumes }}{{ toYaml $mounts_nova_libvirt.volumes | indent 8 }}{{ end }}
