# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- include "neutron.conf.neutron_values_skeleton" .Values.conf.neutron | trunc 0 -}}
{{- include "neutron.conf.dhcp_agent_values_skeleton" .Values.conf.dhcp_agent | trunc 0 -}}
{{- include "neutron.conf.l3_agent_values_skeleton" .Values.conf.l3_agent | trunc 0 -}}
{{- include "neutron.conf.metadata_agent_values_skeleton" .Values.conf.metadata_agent | trunc 0 -}}
{{- include "neutron.conf.metering_agent_values_skeleton" .Values.conf.metering_agent | trunc 0 -}}

{{- include "neutron.conf.linuxbridge_agent_values_skeleton" .Values.conf.linuxbridge_agent | trunc 0 -}}
{{- include "neutron.conf.macvtap_agent_values_skeleton" .Values.conf.macvtap_agent | trunc 0 -}}
{{- include "neutron.conf.ml2_conf_values_skeleton" .Values.conf.ml2_conf | trunc 0 -}}
{{- include "neutron.conf.ml2_conf_sriov_values_skeleton" .Values.conf.ml2_conf_sriov | trunc 0 -}}
{{- include "neutron.conf.openvswitch_agent_values_skeleton" .Values.conf.openvswitch_agent | trunc 0 -}}
{{- include "neutron.conf.sriov_agent_values_skeleton" .Values.conf.sriov_agent | trunc 0 -}}

{{- if empty .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token.auth_uri -}}
{{- tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token "auth_uri" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token.auth_url -}}
{{- tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token "auth_url" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token.memcached_servers -}}
{{- tuple "oslo_cache" "internal" "memcache" . | include "helm-toolkit.endpoints.hostname_endpoint_uri_lookup" | set .Values.conf.neutron.keystone_authtoken.keystonemiddleware.auth_token "memcached_servers" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.neutron.database.oslo.db.connection -}}
{{- tuple "oslo_db" "internal" "user" "mysql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup"| set .Values.conf.neutron.database.oslo.db "connection" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.neutron.default.oslo.messaging.transport_url -}}
{{- tuple "oslo_messaging" "internal" "user" "amqp" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" | set .Values.conf.neutron.default.oslo.messaging "transport_url" | quote | trunc 0 -}}
{{- end }}

{{- if empty .Values.conf.neutron.nova.nova.auth.auth_url -}}
{{- tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.neutron.nova.nova.auth "auth_url" | quote | trunc 0 -}}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc
data:
  api-paste.ini: |+
{{ if .Values.conf.paste.override -}}
{{ .Values.conf.paste.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.paste.prefix -}}
{{ .Values.conf.paste.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_api-paste.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.paste.append -}}
{{ .Values.conf.paste.append | indent 4 }}
{{- end }}
  policy.json: |+
{{ if .Values.conf.policy.override -}}
{{ .Values.conf.policy.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.policy.prefix -}}
{{ .Values.conf.policy.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_policy.json.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.policy.append -}}
{{ .Values.conf.policy.append | indent 4 }}
{{- end }}
{{- if not .Values.sdn.opencontrail.enabled }}
  dhcp_agent.ini: |+
{{ if .Values.conf.dhcp_agent.override -}}
{{ .Values.conf.dhcp_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.dhcp_agent.prefix -}}
{{ .Values.conf.dhcp_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_dhcp_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.dhcp_agent.append -}}
{{ .Values.conf.dhcp_agent.append | indent 4 }}
{{- end }}
  l3_agent.ini: |+
{{ if .Values.conf.l3_agent.override -}}
{{ .Values.conf.l3_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.l3_agent.prefix -}}
{{ .Values.conf.l3_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_l3_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.l3_agent.append -}}
{{ .Values.conf.l3_agent.append | indent 4 }}
{{- end }}
  metadata_agent.ini: |+
{{ if .Values.conf.metadata_agent.override -}}
{{ .Values.conf.metadata_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.metadata_agent.prefix -}}
{{ .Values.conf.metadata_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_metadata_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.metadata_agent.append -}}
{{ .Values.conf.metadata_agent.append | indent 4 }}
{{- end }}
  metering_agent.ini: |+
{{ if .Values.conf.metering_agent.override -}}
{{ .Values.conf.metering_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.metering_agent.prefix -}}
{{ .Values.conf.metering_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_metering_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.metering_agent.append -}}
{{ .Values.conf.metering_agent.append | indent 4 }}
{{- end }}
  ml2_conf.ini: |+
{{ if .Values.conf.ml2_conf.override -}}
{{ .Values.conf.ml2_conf.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.ml2_conf.prefix -}}
{{ .Values.conf.ml2_conf.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_ml2_conf.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.ml2_conf.append -}}
{{ .Values.conf.ml2_conf.append | indent 4 }}
{{- end }}
  ml2_conf_sriov.ini: |+
{{ if .Values.conf.ml2_conf_sriov.override -}}
{{ .Values.conf.ml2_conf_sriov.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.ml2_conf_sriov.prefix -}}
{{ .Values.conf.ml2_conf_sriov.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_ml2_conf_sriov.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.ml2_conf_sriov.append -}}
{{ .Values.conf.ml2_conf_sriov.append | indent 4 }}
{{- end }}
  macvtap_agent.ini: |+
{{ if .Values.conf.macvtap_agent.override -}}
{{ .Values.conf.macvtap_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.macvtap_agent.prefix -}}
{{ .Values.conf.macvtap_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_macvtap_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.macvtap_agent.append -}}
{{ .Values.conf.macvtap_agent.append | indent 4 }}
{{- end }}
  linuxbridge_agent.ini: |+
{{ if .Values.conf.linuxbridge_agent.override -}}
{{ .Values.conf.linuxbridge_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.linuxbridge_agent.prefix -}}
{{ .Values.conf.linuxbridge_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_linuxbridge_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.linuxbridge_agent.append -}}
{{ .Values.conf.linuxbridge_agent.append | indent 4 }}
{{- end }}
  openvswitch_agent.ini: |+
{{ if .Values.conf.openvswitch_agent.override -}}
{{ .Values.conf.openvswitch_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.openvswitch_agent.prefix -}}
{{ .Values.conf.openvswitch_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_openvswitch_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.openvswitch_agent.append -}}
{{ .Values.conf.openvswitch_agent.append | indent 4 }}
{{- end }}
  sriov_agent.ini: |+
{{ if .Values.conf.sriov_agent.override -}}
{{ .Values.conf.sriov_agent.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.sriov_agent.prefix -}}
{{ .Values.conf.sriov_agent.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/plugins/_sriov_agent.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.sriov_agent.append -}}
{{ .Values.conf.sriov_agent.append | indent 4 }}
{{- end }}
{{- else }}
  opencontrail_plugin.ini: |+
{{- if .Values.conf.opencontrail.override -}}
{{ .Values.conf.neutron.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.opencontrail.prefix -}}
{{ .Values.conf.neutron.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_opencontrail_plugin.ini.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.opencontrail.append -}}
{{ .Values.conf.opencontrail.append | indent 4 }}
{{- end }}
{{- end }}
  neutron.conf: |+
{{ if .Values.conf.neutron.override -}}
{{ .Values.conf.neutron.override | indent 4 }}
{{- else -}}
{{- if .Values.conf.neutron.prefix -}}
{{ .Values.conf.neutron.prefix | indent 4 }}
{{- end }}
{{ tuple "etc/_neutron.conf.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.conf.neutron.append -}}
{{ .Values.conf.neutron.append | indent 4 }}
{{- end }}
  resolv.conf: |+
{{ tuple "etc/_resolv.conf.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  dnsmasq.conf: ""

