# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if not .Values.sdn.opencontrail.enabled }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.l3 }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-l3-agent
spec:
  template:
    metadata:
      labels:
        app: neutron-l3-agent
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.agent.l3.node_selector_key }}: {{ .Values.labels.agent.l3.node_selector_value }}
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: neutron-l3-agent
          image: {{ .Values.images.l3 }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.agent.l3.limits.cpu | quote }}
              memory: {{ .Values.resources.agent.l3.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.agent.l3.requests.cpu | quote }}
              memory: {{ .Values.resources.agent.l3.requests.memory | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /tmp/neutron-l3-agent.sh
          volumeMounts:
            - name: neutron-bin
              mountPath: /tmp/neutron-l3-agent.sh
              subPath: neutron-l3-agent.sh
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/ml2_conf.ini
              subPath: ml2_conf.ini
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/openvswitch_agent.ini
              subPath: openvswitch_agent.ini
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/l3_agent.ini
              subPath: l3_agent.ini
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
              readOnly: true
            - name: runopenvswitch
              mountPath: /run/openvswitch
            - name: socket
              mountPath: /var/lib/neutron/stackanetes
      volumes:
        - name: neutron-bin
          configMap:
            name: neutron-bin
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: runopenvswitch
          hostPath:
            path: /run/openvswitch
        - name: socket
          hostPath:
            path: /var/lib/neutron/stackanetes
{{- end }}
