# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if not .Values.sdn.opencontrail.enabled }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.ovs_agent }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ovs-agent
spec:
  template:
    metadata:
      labels:
        app: ovs-agent
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.ovs.node_selector_key }}: {{ .Values.labels.ovs.node_selector_value }}
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: ovs-agent
          image: {{ .Values.images.neutron_openvswitch_agent }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.ovs.agent.limits.cpu | quote }}
              memory: {{ .Values.resources.ovs.agent.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.ovs.agent.requests.cpu | quote }}
              memory: {{ .Values.resources.ovs.agent.requests.memory | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /tmp/neutron-openvswitch-agent.sh
          # ensures this container can can see a br-int
          # bridge before its marked as ready
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - 'ovs-vsctl list-br | grep -q br-int'
          volumeMounts:
            - name: neutron-bin
              mountPath: /tmp/neutron-openvswitch-agent.sh
              subPath: neutron-openvswitch-agent.sh
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/ml2_conf.ini
              subPath: ml2_conf.ini
              readOnly: true
            - name: neutron-etc
              mountPath: /etc/neutron/plugins/ml2/openvswitch_agent.ini
              subPath: openvswitch_agent.ini
              readOnly: true
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: run
              mountPath: /run
            - name: neutron-etc
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
      volumes:
        - name: varlibopenvswitch
          emptyDir: {}
        - name: neutron-bin
          configMap:
            name: neutron-bin
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run
{{- end }}
