{{- if .Values.manifests.daemonset_controller }}
{{- $envAll := . }}
# host_os is a mandatory field
{{- $_ := required ".Values.conf.host_os must be specified, valid values are ubuntu, centos" .Values.conf.host_os }}
{{- $suffix_obj_name := .Values.conf.suffix_obj_name | default "" }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-controller{{- $suffix_obj_name }}
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" (printf "controller%s" $suffix_obj_name | quote) | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.controller.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.controller.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-controller
        image: {{ .Values.images.tags.controller | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
          - name: contrailctl-controller
            mountPath: /etc/contrailctl/controller.conf
            subPath: controller.conf
          - name: controller-bin
            mountPath: /tmp/controller-readiness.sh
            subPath: controller-readiness.sh
          - name: configdb-data
            mountPath: /var/lib/cassandra
          - name: zookeeper-data
            mountPath: /var/lib/zookeeper
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 500
          exec:
            command:
              - /tmp/controller-readiness.sh
      volumes:
      - name: contrailctl-controller
        configMap:
          name: configmap-contrailctl{{- $suffix_obj_name }}
          defaultMode: 0444
      - name: controller-bin
        configMap:
          name: controller-bin{{ $suffix_obj_name }}
          defaultMode: 0555
      - name: configdb-data
        hostPath:
          path: /var/lib/configdb
      - name: zookeeper-data
        hostPath:
          path: /var/lib/config_zookeeper_data
{{- end }}
