{{- if .Values.manifests.daemonset_analytics }}
{{- $envAll := . }}
# host_os is a mandatory field
{{- $_ := required ".Values.conf.host_os must be specified, valid values are ubuntu, centos" .Values.conf.host_os }}
{{- $suffix_obj_name := .Values.conf.suffix_obj_name | default "" }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics{{- $suffix_obj_name }}
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "opencontrail" (printf "analytics%s" $suffix_obj_name | quote) | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analytics.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analytics.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analytics
        image: {{ .Values.images.tags.analytics | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: contrailctl-analytics
          mountPath: /etc/contrailctl/analytics.conf
          subPath: analytics.conf
        - name: controller-bin
          mountPath: /tmp/analytics-readiness.sh
          subPath: analytics-readiness.sh
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 500
          exec:
            command:
              - /tmp/analytics-readiness.sh
      volumes:
      - name: contrailctl-analytics
        configMap:
          name: configmap-contrailctl{{ $suffix_obj_name }}
          defaultMode: 0444
      - name: controller-bin
        configMap:
          name: controller-bin{{ $suffix_obj_name }}
          defaultMode: 0555
{{- end }}
