{{- if .Values.manifests.rbac_contrail }}
# host_os is a mandatory field
{{- $_ := required ".Values.conf.host_os must be specified, valid values are ubuntu, centos" .Values.conf.host_os }}
{{- $suffix_obj_name := .Values.conf.suffix_obj_name | default "" }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-kube-manager{{- $suffix_obj_name }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-kube-manager{{- $suffix_obj_name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contrail-kube-manager{{- $suffix_obj_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-kube-manager{{- $suffix_obj_name }}
subjects:
- kind: ServiceAccount
  name: contrail-kube-manager{{- $suffix_obj_name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-kube-manager-token{{- $suffix_obj_name }}
  annotations:
    helm.sh/hook: post-install
    kubernetes.io/service-account.name: contrail-kube-manager{{- $suffix_obj_name }}
type: kubernetes.io/service-account-token
---
{{- end }}
