# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  db_init: kolla/ubuntu-source-kolla-toolbox:3.0.2
  db_sync: kolla/ubuntu-source-keystone:2.0.2
  api: kolla/ubuntu-source-keystone:2.0.2
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.1
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

keystone:
  version: v3
  scheme: http
  admin_region_name: RegionOne
  admin_user: admin
  admin_password: password
  admin_project_name: admin

network:
  port:
    admin: 35357
    api: 5000

dependencies:
  api:
    jobs:
    - mariadb-seed
    - keystone-db-sync
    service:
    - mariadb
  db_sync:
    jobs:
    - keystone-db-init
    - mariadb-seed
    service:
    - mariadb
  init:
    jobs:
    - mariadb-seed
    service:
    - mariadb

resources:
  enabled: false
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
  jobs:
    db_sync:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    init:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"

mounts:
  keystone_db_init:
    init_container: null
    keystone_db_init:     
      volumes:
      - name: keystone-bin
        configMap:
          name: keystone-bin      
      volumeMounts:
      - name: keystone-bin
        mountPath: /tmp/init.sh
        subPath: init.sh
  keystone_db_sync:
    init_container: null
    keystone_db_sync:
      volumes:
      - name: empty
        emptyDir: {}
      - name: keystone-etc
        configMap:
          name: keystone-etc
      - name: keystone-bin
        configMap:
          name: keystone-bin      
      volumeMounts:
      - name: empty
        mountPath: /etc/keystone
      - name: keystone-etc
        mountPath: /etc/keystone/keystone.conf
        subPath: keystone.conf
        readOnly: true
      - name: keystone-bin
        mountPath: /tmp/db-sync.sh
        subPath: db-sync.sh
        readOnly: true  
  keystone_api:
    init_container: null
    keystone_api:
      volumes:
      - name: empty
        emptyDir: {}
      - name: keystone-etc
        configMap:
          name: keystone-etc
      - name: keystone-bin
        configMap:
          name: keystone-bin     
      volumeMounts:
      - name: empty
        mountPath: /etc/keystone
      - name: keystone-etc
        mountPath: /etc/keystone/keystone.conf
        subPath: keystone.conf
        readOnly: true
      - name: keystone-etc
        mountPath: /etc/keystone/keystone-paste.ini
        subPath: keystone-paste.ini
        readOnly: true
      - name: keystone-etc
        mountPath: /etc/keystone/policy.json
        subPath: policy.json
        readOnly: true
      - name: keystone-etc
        mountPath: /etc/keystone/sso_callback_template.html
        subPath: sso_callback_template.html
        readOnly: true
      - name: keystone-etc
        mountPath: /etc/apache2/conf-enabled/wsgi-keystone.conf
        subPath: wsgi-keystone.conf
        readOnly: true
      - name: keystone-etc
        mountPath: /etc/apache2/mods-available/mpm_event.conf
        subPath: mpm_event.conf
        readOnly: true
      - name: keystone-bin
        mountPath: /tmp/start.sh
        subPath: start.sh
        readOnly: true      

conf:
  paste:
    override: |+
      # Keystone PasteDeploy configuration file.
      
      [filter:debug]
      use = egg:oslo.middleware#debug
      
      [filter:request_id]
      use = egg:oslo.middleware#request_id
      
      [filter:build_auth_context]
      use = egg:keystone#build_auth_context
      
      [filter:token_auth]
      use = egg:keystone#token_auth
      
      [filter:admin_token_auth]
      # This is deprecated in the M release and will be removed in the O release.
      # Use `keystone-manage bootstrap` and remove this from the pipelines below.
      use = egg:keystone#admin_token_auth
      
      [filter:json_body]
      use = egg:keystone#json_body
      
      [filter:cors]
      use = egg:oslo.middleware#cors
      oslo_config_project = keystone
      
      [filter:ec2_extension]
      use = egg:keystone#ec2_extension
      
      [filter:ec2_extension_v3]
      use = egg:keystone#ec2_extension_v3
      
      [filter:s3_extension]
      use = egg:keystone#s3_extension
      
      [filter:url_normalize]
      use = egg:keystone#url_normalize
      
      [filter:sizelimit]
      use = egg:oslo.middleware#sizelimit
      
      [app:public_service]
      use = egg:keystone#public_service
      
      [app:service_v3]
      use = egg:keystone#service_v3
      
      [app:admin_service]
      use = egg:keystone#admin_service
      
      [pipeline:public_api]
      # The last item in this pipeline must be public_service or an equivalent
      # application. It cannot be a filter.
      pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension public_service
      
      [pipeline:admin_api]
      # The last item in this pipeline must be admin_service or an equivalent
      # application. It cannot be a filter.
      pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension s3_extension admin_service
      
      [pipeline:api_v3]
      # The last item in this pipeline must be service_v3 or an equivalent
      # application. It cannot be a filter.
      pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension_v3 s3_extension service_v3
      
      [app:public_version_service]
      use = egg:keystone#public_version_service
      
      [app:admin_version_service]
      use = egg:keystone#admin_version_service
      
      [pipeline:public_version_api]
      pipeline = cors sizelimit url_normalize public_version_service
      
      [pipeline:admin_version_api]
      pipeline = cors sizelimit url_normalize admin_version_service
      
      [composite:main]
      use = egg:Paste#urlmap
      /v2.0 = public_api
      /v3 = api_v3
      / = public_version_api
      
      [composite:admin]
      use = egg:Paste#urlmap
      /v2.0 = admin_api
      /v3 = api_v3
      / = admin_version_api
    append:
  policy:
    override:
    append:
  keystone:
    override: |+
      # Copyright 2017 The Openstack-Helm Authors.
      #
      # Licensed under the Apache License, Version 2.0 (the "License");
      # you may not use this file except in compliance with the License.
      # You may obtain a copy of the License at
      #
      #     http://www.apache.org/licenses/LICENSE-2.0
      #
      # Unless required by applicable law or agreed to in writing, software
      # distributed under the License is distributed on an "AS IS" BASIS,
      # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      # See the License for the specific language governing permissions and
      # limitations under the License.
      
      [DEFAULT]
      use_syslog = False
      use_stderr = True
      
      [database]
      connection = mysql+pymysql://keystone:password@mariadb/keystone
      max_retries = -1
      
      [memcache]
      servers = memcached:11211
      
      [token]
      provider = uuid
      
      [cache]
      backend = dogpile.cache.memcached
      memcache_servers = memcached:11211
      config_prefix = cache.keystone
      enabled = True
    append:
    token: 
      keystone:
        provider: uuid
    database:
      oslo:
        db:
          max_retries: -1

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    name: keystone
    hosts:
      default: keystone-api
    path: /v3
    scheme: 'http'
    port:
      admin: 35357
      api: 5000
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: keystone
        password: password
    hosts:
      default: mariadb
    path: /keystone
    scheme: mysql+pymysql
    port:
      mysql: 3306
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: keystone
        password: password
    hosts:
      default: rabbitmq
    path: /openstack
    scheme: rabbit
    port:
      amqp: 5672  
  oslo_cache:
    hosts:
      default: memcache
    port:
      memcache: 11211
