# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  bootstrap: docker.io/kolla/ubuntu-source-keystone:4.0.0
  test: docker.io/kolla/ubuntu-binary-rally:4.0.0
  db_init: docker.io/kolla/ubuntu-source-keystone:4.0.0
  db_sync: docker.io/kolla/ubuntu-source-keystone:4.0.0
  api: docker.io/kolla/ubuntu-source-keystone:4.0.0
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

pod_disruption_budget:
  api:
    min_available: 0

termination_grace_period:
  api:
    timeout: 30

keystone:
  version: v3
  scheme: http
  admin_region_name: RegionOne
  admin_user: admin
  admin_password: password
  admin_project_name: admin
  admin_user_domain: default
  admin_project_domain: default

bootstrap:
  enabled: false
  script: null

network:
  api:
    name: "keystone-api"
    port: 5000
    node_port:
      enabled: false
      port: 30500
  admin:
    name: "keystone-admin"
    port: 35357
    node_port:
      enabled: false
      port: 30357

dependencies:
  api:
    jobs:
    - keystone-db-sync
    service:
    - mariadb
  db_sync:
    jobs:
    - keystone-db-init
    service:
    - mariadb
  init:
    service:
    - mariadb
  tests:
    service:
    - keystone-api
  bootstrap:
    service:
    - keystone-api

resources:
  enabled: false
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
  jobs:
    bootstrap:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    db_sync:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    init:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
  tests:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"

mounts:
  keystone_db_init:
    init_container: null
    keystone_db_init:
  keystone_db_sync:
    init_container: null
    keystone_db_sync:
  keystone_api:
    init_container: null
    keystone_api:
  keystone_tests:
    init_container: null
    keystone_tests:
  keystone_bootstrap:
    init_container: null
    keystone_bootstrap:

conf:
  rally_tests:
    override:
    append:
  paste:
    override:
    append:
  policy:
    override:
    append:
  keystone:
    override:
    append:
    default:
      keystone:
        max_token_size: 32
    token:
      keystone:
        provider: uuid
    database:
      oslo:
        db:
          max_retries: -1
    cache:
      oslo:
        cache:
          enabled: true
          backend: dogpile.cache.memcached

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    name: keystone
    hosts:
      default: keystone-api
    path: /v3
    scheme: 'http'
    port:
      admin: 35357
      api: 5000
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: keystone
        password: password
    hosts:
      default: mariadb
    path: /keystone
    scheme: mysql+pymysql
    port:
      mysql: 3306
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: keystone
        password: password
    hosts:
      default: rabbitmq
    path: /openstack
    scheme: rabbit
    port:
      amqp: 5672
  oslo_cache:
    hosts:
      default: memcache
    port:
      memcache: 11211
