# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for glance.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# ceph or pvc
storage: ceph

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

release_group: null

images:
  test: docker.io/kolla/ubuntu-binary-rally:4.0.0
  db_init: docker.io/kolla/ubuntu-source-glance-api:3.0.3
  db_sync: docker.io/kolla/ubuntu-source-glance-api:3.0.3
  ks_user: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_service: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_endpoints: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  api: docker.io/kolla/ubuntu-source-glance-api:3.0.3
  registry: docker.io/kolla/ubuntu-source-glance-registry:3.0.3
  bootstrap: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  pull_policy: "IfNotPresent"

bootstrap:
  enabled: true
  images:
    cirros:
      id: null
      name: "Cirros 0.3.5 64-bit"
      source_url: "http://download.cirros-cloud.net/0.3.5/"
      image_file: "cirros-0.3.5-x86_64-disk.img"
      min_disk: 1
      image_type: qcow2
      container_format: bare
      private: true
      properties:
        hypervisor_type: "qemu"
        os_distro: "cirros"

conf:
  rally_tests:
    override:
    append:
    images:
      image_location: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
      disk_format: qcow2
      container_format: bare
  ceph:
    monitors: []
    keyring: null
    override:
    append:
  ceph_client:
    override:
    append:
  paste:
    override:
    append:
  policy:
    override:
    append:
  glance:
    override:
    append:
    default:
      glance:
        api:
          bind_port: 9292
    keystone_authtoken:
      keystonemiddleware:
        auth_token:
          auth_type: password
          auth_version: v3
    glance_store:
      glance:
        store:
          stores: file, http, rbd
          default_store: rbd
          rbd_store_chunk_size: 8
          rbd_store_pool: images
          rbd_store_user: admin
          rbd_store_ceph_conf: /etc/ceph/ceph.conf
          filesystem_store_datadir: /var/lib/glance/images
    paste_deploy:
      glance:
        api:
          flavor: keystone
  paste_registry:
    override:
    append:
  glance_registry:
    override:
    append:
    default:
      glance:
        registry:
          bind_port: 9191
    keystone_authtoken:
      keystonemiddleware:
        auth_token:
          auth_type: password
          auth_version: v3
    paste_deploy:
      glance:
        registry:
          flavor: keystone

network:
  api:
    ingress:
      public: true
      proxy_body_size: 1024M
    node_port:
      enabled: false
      port: 30092
  registry:
    ingress:
      public: true
    node_port:
      enabled: false
      port: 30091

volume:
  class_name: general
  size: 2Gi
  storage_path: /var/lib/localkube/glance

dependencies:
  db_init:
    services:
    - service: oslo_db
      endpoint: internal
  db_sync:
    jobs:
    - glance-db-init
    services:
    - service: oslo_db
      endpoint: internal
  bootstrap:
    jobs:
    - glance-db-sync
    - glance-ks-user
    - glance-ks-endpoints
    services:
    - service: identity
      endpoint: internal
    - service: image
      endpoint: internal
  ks_user:
    services:
    - service: identity
      endpoint: internal
  ks_service:
    services:
    - service: identity
      endpoint: internal
  ks_endpoints:
    jobs:
    - glance-ks-service
    services:
    - service: identity
      endpoint: internal
  api:
    jobs:
    - glance-db-sync
    - glance-ks-user
    - glance-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
  registry:
    jobs:
    - glance-db-sync
    - glance-ks-user
    - glance-ks-endpoints
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
    - service: image
      endpoint: internal
  tests:
    services:
    - service: oslo_db
      endpoint: internal
    - service: identity
      endpoint: internal
    - service: image
      endpoint: internal

# Names of secrets used by bootstrap and environmental checks
secrets:
  identity:
    admin: glance-keystone-admin
    user: glance-keystone-user
  oslo_db:
    admin: glance-db-admin
    user: glance-db-user

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      user:
        role: admin
        region_name: RegionOne
        username: glance
        password: password
        project_name: service
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
  image:
    name: glance
    hosts:
      default: glance-api
      public: glance
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9292
        public: 80
  image_registry:
    name: glance-registry
    hosts:
      default: glance-registry
      public: glance-reg
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9191
        public: 80
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: glance
        password: password
    hosts:
      default: mariadb
    path: /glance
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_cache:
    hosts:
      default: memcached
    port:
      memcache:
        default: 11211
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    hosts:
      default: rabbitmq
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672

pod:
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  mounts:
    glance_api:
      init_container: null
      glance_api:
    glance_registry:
      init_container: null
      glance_registry:
    glance_tests:
      init_container: null
      glance_tests:
  replicas:
    api: 1
    registry: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    disruption_budget:
      api:
        min_available: 0
      registry:
        min_available: 0
    termination_grace_period:
      api:
        timeout: 600
      registry:
        timeout: 600
  resources:
    enabled: false
    api:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    registry:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      db_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_init:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_user:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_service:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_endpoints:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      bootstrap:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      tests:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

manifests:
  configmap_bin: true
  configmap_etc: true
  deployment_api: true
  deployment_registry: true
  ingress_api: true
  ingress_registry: true
  job_bootstrap: true
  job_clean: true
  job_db_init: true
  job_db_sync: true
  job_ks_endpoints: true
  job_ks_service: true
  job_ks_user: true
  pdb_api: true
  pdb_registry: true
  pod_rally_test: true
  pvc_images: true
  secret_db: true
  secret_keystone: true
  service_ingress_api: true
  service_ingress_registry: true
  service_api: true
  service_registry: true
