{{- if .Values.manifests.configmap_contrailctl }}
{{- $envAll := . }}
{{- $cloud_orchestrator := .Values.conf.global_config.GLOBAL.cloud_orchestrator }}


{{- if empty .Values.conf.keystone_config.KEYSTONE.auth_url -}}
{{- tuple "identity" "internal" "admin" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.keystone_config.KEYSTONE "auth_url" | quote | trunc 0 -}}
{{- end }}
{{- if empty .Values.conf.keystone_config.KEYSTONE.ip -}}
{{- tuple "identity" "internal" $envAll | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" | set .Values.conf.keystone_config.KEYSTONE "ip" | quote | trunc 0 -}}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: contrailctl-vrouter-config
data:
  global.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.global_config | indent 4 }}

  kubemanager.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.kubemanager_config | indent 4 }}

  kubernetesagent.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.kubernetesagent_config | indent 4 }}

  agent.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.agent_config | indent 4 }}

{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.keystone_config | indent 4 }}

{{- end }}
